[project]
name = "assignments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Farhankhan1", email = "enggfarhan36@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.6",
]

[project.scripts]
assignments = "assignments:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
